### ISSUE TITLE
Feedback for /docs/latest/python/python-appapi-devguide/

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#92]
# @wmarshall484  @juliabamford

"Install a supported version of Python:

CPython 3.5.0 or later https://www.python.org.

Anaconda 4.0.0 or later, which includes Python 3.5.0 https://www.continuum.io/downloads."

For this documentation here, do I need both CPython and Anaconda?  or only one of them?  How do I check if my environment already have these installed?

**Comment by wmarshall484** [comment]
You only need one of them. At present, it's important that you're using Python 3.5, and that the locations of your libpython3.5.so libraries are included in your LD_LIBRARY_PATH:

If you installed with Anaconda, then typing `python` should return something like:
```bash
/home/chanskw/anaconda/bin/python
```

Otherwise, you're likely using CPython.

**Comment by natashadsilva** [comment]
The doc has been updated to state that they need to choose from one of the installation options.
